import Head from "next/head";
import React from "react";

import TopBar from "../Components/TopBar";
import FixedFooter from "../Components/FixedFooter";
import HomeContent from "../Components/HomeContent";
import { AppSharedContext } from "../Context/AppContext";

export default function Home() {
  const { authProvider } = React.useContext(AppSharedContext);

  React.useEffect(() => {
    authProvider.isAuth();
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app " />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <TopBar />
        <HomeContent />
        <FixedFooter />
      </main>
    </>
  );
}
